name: Deploy PWA Template

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 4.1.0)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Deploy with version management
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          node deploy.js ${{ github.event.inputs.version }}
        else
          node deploy.js --patch
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          PWA Template Release ${{ github.ref }}
          
          ## What's New
          - Enhanced auto-updater and cache management
          - Improved browser caching strategy
          - Added version control and update notifications
          - Better offline support and cache management
          
          ## Installation
          Visit the deployed PWA at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          
          The PWA will automatically update for existing users.
        draft: false
        prerelease: false
